### PR TITLE
Isaac only

### PR DESCRIPTION
**Pull request by alandekok**
These changes should address all open issues. 

FNV has been removed, as it is no longer necessary.

The discussion of seeding ISAAC has been updated, and sample output has been given.

The code has been updated.

### CODE REVIEW

**Review by mjethanandani — COMMENTED** [review]
Hi @alandekok , thanks for submitting these changes. I am seeing the following issues in the draft.

xml2rfc draft-ietf-bfd-secure-sequence-numbers-09.xml -o draft-ietf-bfd-secure-sequence-numbers-09.txt --text
Error: Unable to parse the XML document: draft-ietf-bfd-secure-sequence-numbers-09.xml
 /app/draft/draft-ietf-bfd-secure-sequence-numbers-09.xml: Line 456: Opening and ending tag mismatch: t line 422 and section
 /app/draft/draft-ietf-bfd-secure-sequence-numbers-09.xml: Line 456: Opening and ending tag mismatch: t line 422 and section
 /app/draft/draft-ietf-bfd-secure-sequence-numbers-09.xml: Line 635: Opening and ending tag mismatch: t line 554 and section
 /app/draft/draft-ietf-bfd-secure-sequence-numbers-09.xml: Line 641: Opening and ending tag mismatch: section line 549 and middle
 /app/draft/draft-ietf-bfd-secure-sequence-numbers-09.xml: Line 664: Opening and ending tag mismatch: section line 293 and rfc
 /app/draft/draft-ietf-bfd-secure-sequence-numbers-09.xml: Line 665: Premature end of data in tag middle line 163
make: *** [Makefile:60: draft-ietf-bfd-secure-sequence-numbers-09.txt] Error 1
make: *** [container] Error 2

**Comment by mjethanandani** [comment]
Here are the diffs to fix the issues:

diff --git a/draft/draft-ietf-bfd-secure-sequence-numbers.xml b/draft/draft-ietf-bfd-secure-sequence-numbers.xml
index f41f2f6..bc1fbd6 100644
--- a/draft/draft-ietf-bfd-secure-sequence-numbers.xml
+++ b/draft/draft-ietf-bfd-secure-sequence-numbers.xml
@@ -419,7 +419,7 @@
 
     <t>The data is padded to 1024 octets using zeroes, and then is processed throught the "randinit()" function of ISAAC.  Pseudo-random numbers are then produced by calling the "isaac()" function.</t>
 
-    <t>The following figure give Seed and Your-Discriminator as 32-bit hex values, and the Secret Key as an eleven-character string.  The subsequent figure shows the first eight Sequence numbers and corresponding Auth Key values which were generated using the above initial values.
+    <t>The following figure give Seed and Your-Discriminator as 32-bit hex values, and the Secret Key as an eleven-character string.  The subsequent figure shows the first eight Sequence numbers and corresponding Auth Key values which were generated using the above initial values.</t>
 
       <figure>
           <artwork><![CDATA[     
@@ -551,7 +551,7 @@ Sequence Auth Key
       of the Secret Key, and on its entropy.  It is RECOMMENDED
       that the key be 16 octets in length or more.</t>
 
-      <t>The dependency on the Secret Key for security is mitigated through the use of two 32-bit random numbers, with one generated by each party to a BFD session.  An attacker cannot simply perform an off-line brute-force dictionary attack to discover the key.  Instead, any analysis has to include the particular 64 bits of entropy used for a particular session.  As a result, dictionary attacks are more difficult than they would be if the PRNG generator depended on nothing more than the Secret Key.
jethanandan-a01:bfd-secure-sequence-numbers mahesh$ git diff > diff
jethanandan-a01:bfd-secure-sequence-numbers mahesh$ cat diff
diff --git a/draft/draft-ietf-bfd-secure-sequence-numbers.xml b/draft/draft-ietf-bfd-secure-sequence-numbers.xml
index f41f2f6..bc1fbd6 100644
--- a/draft/draft-ietf-bfd-secure-sequence-numbers.xml
+++ b/draft/draft-ietf-bfd-secure-sequence-numbers.xml
@@ -419,7 +419,7 @@
 
     <t>The data is padded to 1024 octets using zeroes, and then is processed throught the "randinit()" function of ISAAC.  Pseudo-random numbers are then produced by calling the "isaac()" function.</t>
 
-    <t>The following figure give Seed and Your-Discriminator as 32-bit hex values, and the Secret Key as an eleven-character string.  The subsequent figure shows the first eight Sequence numbers and corresponding Auth Key values which were generated using the above initial values.
+    <t>The following figure give Seed and Your-Discriminator as 32-bit hex values, and the Secret Key as an eleven-character string.  The subsequent figure shows the first eight Sequence numbers and corresponding Auth Key values which were generated using the above initial values.</t>
 
       <figure>
           <artwork><![CDATA[	  
@@ -551,7 +551,7 @@ Sequence Auth Key
       of the Secret Key, and on its entropy.  It is RECOMMENDED
       that the key be 16 octets in length or more.</t>
 
-      <t>The dependency on the Secret Key for security is mitigated through the use of two 32-bit random numbers, with one generated by each party to a BFD session.  An attacker cannot simply perform an off-line brute-force dictionary attack to discover the key.  Instead, any analysis has to include the particular 64 bits of entropy used for a particular session.  As a result, dictionary attacks are more difficult than they would be if the PRNG generator depended on nothing more than the Secret Key.
+      <t>The dependency on the Secret Key for security is mitigated through the use of two 32-bit random numbers, with one generated by each party to a BFD session.  An attacker cannot simply perform an off-line brute-force dictionary attack to discover the key.  Instead, any analysis has to include the particular 64 bits of entropy used for a particular session.  As a result, dictionary attacks are more difficult than they would be if the PRNG generator depended on nothing more than the Secret Key.</t>
 
       <t>The security of this proposal depends strongly on ISAAC.
       This generator has been analyzed for almost three decades, and has not been broken.

**Comment by mjethanandani** [comment]
I see that you have moved your position in the authors list. While I do want to acknowledge your (oversized) contribution to the document, allow me to discuss this with the rest of authors to make sure they are ok with it.

**Comment by alandekok** [comment]
On Mar 5, 2023, at 10:26 PM, Mahesh Jethanandani ***@***.***> wrote:
> Here are the diffs to fix the issues:

  That looks good, thanks.

**Comment by mjethanandani** [comment]
> On Mar 5, 2023, at 10:26 PM, Mahesh Jethanandani ***@***.***> wrote: Here are the diffs to fix the issues:
> That looks good, thanks.

Ok. Let me know when you have submitted those changes, so I can approve the commit.

**Comment by alandekok** [comment]
I've pushed changes, and the XML file builds locally.

**Review by mjethanandani — APPROVED** [review]

**Pull request merged**
